=== BVezilic/XML/XML_Projekat/data/akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/skupstina"
    xmlns:sk="http://www.ftn.uns.ac.rs/skupstina">
    <xs:element name="Akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="sk:Preambula"/>
                <xs:element minOccurs="0" ref="sk:Naslov"/>
                <xs:choice>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Deo"/>
                    </xs:sequence>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Clan"/>
                    </xs:sequence>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Preambula"/>
    <xs:element name="Naslov"/>
    <xs:element name="Deo">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Glava"/>
            </xs:sequence>
            <xs:attribute name="Redni_broj" type="xs:int" use="required"/>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Glava">
        <xs:complexType>
            <xs:choice>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" ref="sk:Odeljak"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="Redni_broj" type="xs:int" use="required"/>
            <xs:attribute name="Naziv" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Odeljak">
        <xs:complexType>
            <xs:choice>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" ref="sk:Pododeljak"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Pododeljak">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Clan"/>
            </xs:sequence>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Clan">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="Stavovi" type="sk:StavType"/>
            </xs:sequence>
            <xs:attribute name="Brojcana_oznaka" type="xs:int" use="required"/>
            <xs:attribute name="Naziv" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Stav" type="xs:string"/>
    <xs:element name="Tacka" type="xs:string"/>
    <xs:element name="Podtacka" type="xs:string"/>
    <xs:element name="Alineja" type="xs:string"/>
    <xs:complexType name="StavType">
        <xs:sequence>
            <xs:element ref="sk:Stav"/>
            <xs:sequence minOccurs="0">
                <xs:element maxOccurs="unbounded" minOccurs="2" name="Tacke" type="sk:TackaType"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TackaType">
        <xs:sequence>
            <xs:element ref="sk:Tacka"/>
            <xs:sequence minOccurs="0">
                <xs:element maxOccurs="unbounded" minOccurs="2" name="Podtacke"
                    type="sk:PodtackaType"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PodtackaType">
        <xs:sequence>
            <xs:element ref="sk:Podtacka"/>
            <xs:sequence minOccurs="0">
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Alineja"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== BVezilic/XML/XML_Projekat/data/xml/zakon_o_izvrsenju_i_obezbedjenju.xml
<?xml version="1.0" encoding="UTF-8"?>
<sk:Akt xmlns:sk="http://www.ftn.uns.ac.rs/skupstina"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/skupstina ../xsd/akt.xsd"
    xmlns="http://www.w3.org/ns/rdfa#" 
    xmlns:pred="http://www.ftn.uns.ac.rs/skupstina/predikat">
    <sk:MetaPodaci
        about="http://www.ftn.uns.ac.rs/skupstina/zakon_o_izvrsenju_i_obezbedjenju">
        <sk:DatumPredlaganja property="pred:predlozen" datatype="xsi:date">1999-08-17</sk:DatumPredlaganja>
    </sk:MetaPodaci>
    <sk:Naslov>ZAKON O IZVRŠENjU I OBEZBEĐENjU</sk:Naslov>
    <sk:Deo Redni_broj="1" Redna_oznaka="PRVI" Naziv="OSNOVNE ODREDBE">
        <sk:Clan Redni_broj="1" Redna_oznaka="1." Naziv="Predmet zakona">
            <sk:Stav Redni_broj="1">Ovim zakonom uređuje se postupak u kome sudovi i javni
                izvršitelji prinudno namiruju potraživanja izvršnih poverilaca zasnovana na izvršnim
                i verodostojnim ispravama (izvršni postupak), postupak obezbeđenja potraživanja i
                položaj javnih izvršitelja.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="2" Redna_oznaka="2." Naziv="Značenje pojedinih izraza">
            <sk:Stav Redni_broj="1">Pojedini izrazi koji se koriste u ovom zakonu imaju sledeće
                značenje: <sk:Tacka Redni_broj="1" Redna_oznaka="1)">„potraživanje” označava pravo
                    izvršnog poverioca da zahteva od izvršnog dužnika određeno davanje, činjenje,
                    nečinjenje ili trpljenje;</sk:Tacka>
                <sk:Tacka Redni_broj="2" Redna_oznaka="2)">„izvršni poverilac” označava lice čije se
                    potraživanje namiruje u izvršnom postupku ili obezbeđuje u postupku
                    obezbeđenja;</sk:Tacka>
                <sk:Tacka Redni_broj="3" Redna_oznaka="3)">„izvršni dužnik” označava lice prema kome
                    se potraživanje namiruje u izvršnom postupku ili obezbeđuje u postupku
                    obezbeđenja;</sk:Tacka>
            </sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="3" Redna_oznaka="3."
            Naziv="Pokretanje i vođenje izvršnog postupka i postupka
            obezbeđenja">
            <sk:Stav Redni_broj="1">Izvršni postupak i postupak obezbeđenja pokreću se tako što
                izvršni poverilac podnosi predlog za izvršenje na osnovu izvršne ili verodostojne
                isprave ili predlog za obezbeđenje, a po službenoj dužnosti pokreću se samo ako je
                zakonom određeno.</sk:Stav>
            <sk:Stav Redni_broj="2">O predlogu za izvršenje na osnovu izvršne ili verodostojne
                isprave i predlogu za obezbeđenje odlučuje sud.</sk:Stav>
            <sk:Stav Redni_broj="3">O predlogu za izvršenje na osnovu verodostojne isprave radi
                namirenja novčanog potraživanja nastalog iz komunalnih usluga i srodnih delatnosti
                odlučuje javni izvršitelj.</sk:Stav>
            <sk:Stav Redni_broj="4">Kada se donese rešenje o izvršenju ili obezbeđenju, sprovodi se
                izvršenje.</sk:Stav>
        </sk:Clan>
    </sk:Deo>
    <sk:Deo Redni_broj="2" Redna_oznaka="DRUGI" Naziv="OPŠTA PRAVILA IZVRŠNOG POSTUPKA">
        <sk:Glava Redni_broj="1" Naziv="IZVRŠNA I VERODOSTOJNA ISPRAVA" Redna_oznaka="I.">
            <sk:Odeljak Redni_broj="1" Redna_oznaka="1."
                Naziv="Osnovi za donošenje rešenja o izvršenju">
                <sk:Clan Redni_broj="40" Redna_oznaka="40.">
                    <sk:Stav Redni_broj="1">Rešenje o izvršenju donosi se na osnovu izvršne ili
                        verodostojne isprave.</sk:Stav>
                </sk:Clan>
            </sk:Odeljak>
            <sk:Odeljak Redni_broj="2" Redna_oznaka="2." Naziv="Izvršna isprava">
                <sk:Clan Redni_broj="41" Redna_oznaka="41." Naziv="Vrste izvršnih isprava">
                    <sk:Stav Redni_broj="1">Izvršne isprave jesu: <sk:Tacka Redni_broj="1"
                            Redna_oznaka="1)">izvršna sudska odluka i sudsko poravnanje koji glase
                            na davanje, činjenje, nečinjenje ili trpljenje;</sk:Tacka>
                        <sk:Tacka Redni_broj="2" Redna_oznaka="2)">izvršna odluka doneta u
                            prekršajnom ili upravnom postupku i upravno poravnanje koji glase na
                            novčanu obavezu ako posebnim zakonom nije drukčije određeno;</sk:Tacka>
                        <sk:Tacka Redni_broj="3" Redna_oznaka="3)">izvod iz Registra zaloge i izvod
                            iz Registra finansijskog lizinga;</sk:Tacka>
                    </sk:Stav>
                </sk:Clan>
            </sk:Odeljak>
        </sk:Glava>
        <sk:Glava Redni_broj="2" Naziv="SREDSTVA I PREDMET IZVRŠENjA" Redna_oznaka="II.">
            <sk:Clan Redni_broj="54" Redna_oznaka="54." Naziv="Sredstva izvršenja">
                <sk:Stav Redni_broj="1">Sredstva izvršenja su radnje kojima se namiruje potraživanje
                    izvršnog poverioca.</sk:Stav>
                <sk:Stav Redni_broj="2">Sredstva izvršenja radi namirenja novčanog potraživanja
                    jesu: prodaja nepokretnosti izvršnog dužnika, prodaja pokretnih stvari izvršnog
                    dužnika, prenos novčanog potraživanja izvršnog dužnika, prenos zarade izvršnog
                    dužnika, prenos novčanih sredstava s računa izvršnog dužnika kod banke, prenos
                    sredstava sa štednog uloga ili tekućeg računa izvršnog dužnika, prodaja
                    finansijskih instrumenata izvršnog dužnika, prodaja udela izvršnog dužnika u
                    privrednim subjektima i prenos potraživanja izvršnog dužnika da mu se predaju
                    ili isporuče pokretne stvari ili preda nepokretnost.</sk:Stav>
                <sk:Stav Redni_broj="3">Sredstva izvršenja radi ostvarivanja nenovčanog potraživanja
                    jesu: predaja pokretnih stvari izvršnog dužnika, ispražnjenje i predaja
                    nepokretnosti izvršnog dužnika, činjenje, nečinjenje ili trpljenje izvršnog
                    dužnika, predaja deteta i izvršenje drugih odluka u vezi s porodičnim odnosima,
                    vraćanje zaposlenog na rad, deoba suvlasničke stvari i izdejstvovanje izjave
                    volje.</sk:Stav>
            </sk:Clan>
        </sk:Glava>
        <sk:Glava Redni_broj="3" Naziv="PREDLOG ZA IZVRŠENjE I REŠENjE O IZVRŠENjU"
            Redna_oznaka="III.">
            <sk:Odeljak Redni_broj="1" Redna_oznaka="1." Naziv="Predlog za izvršenje">
                <sk:Clan Redni_broj="59" Redna_oznaka="59."
                    Naziv="Predlog za izvršenje na osnovu izvršne isprave">
                    <sk:Stav Redni_broj="1">U predlogu za izvršenje naznačavaju se identifikacioni
                        podaci o izvršnom poveriocu i izvršnom dužniku (član 30), izvršna isprava,
                        potraživanje izvršnog poverioca, jedno sredstvo ili jedan predmet ili više
                        sredstava i predmeta izvršenja, i drugi podaci koji su potrebni za
                        sprovođenje izvršenja.</sk:Stav>
                    <sk:Stav Redni_broj="2">Uz predlog za izvršenje prilaže se izvršna isprava u
                        originalu, overenoj kopiji ili prepisu, i druga isprava određena ovim
                        zakonom, s tim što izvršna isprava mora da sadrži potvrdu o
                        izvršnosti.</sk:Stav>
                    <sk:Stav Redni_broj="3">Ali ako se predlog za izvršenje podnosi sudu koji je u
                        prvom stepenu odlučivao o potraživanju izvršnog poverioca, uz njega se ne
                        prilaže izvršna isprava, a i ako se priloži, ne mora da sadrži potvrdu o
                        izvršnosti.</sk:Stav>
                    <sk:Stav Redni_broj="4">Predlog za izvršenje podnosi se najmanje u četiri
                        primerka.</sk:Stav>
                </sk:Clan>
            </sk:Odeljak>
        </sk:Glava>
    </sk:Deo>
</sk:Akt>
