=== BVezilic/XML/XML_Projekat/data/akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/skupstina"
    xmlns:sk="http://www.ftn.uns.ac.rs/skupstina">
    <xs:element name="Akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="sk:Preambula"/>
                <xs:element minOccurs="0" ref="sk:Naslov"/>
                <xs:choice>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Deo"/>
                    </xs:sequence>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Clan"/>
                    </xs:sequence>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Preambula"/>
    <xs:element name="Naslov"/>
    <xs:element name="Deo">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Glava"/>
            </xs:sequence>
            <xs:attribute name="Redni_broj" type="xs:int" use="required"/>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Glava">
        <xs:complexType>
            <xs:choice>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" ref="sk:Odeljak"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="Redni_broj" type="xs:int" use="required"/>
            <xs:attribute name="Naziv" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Odeljak">
        <xs:complexType>
            <xs:choice>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" ref="sk:Pododeljak"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Pododeljak">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Clan"/>
            </xs:sequence>
            <xs:attribute name="Naziv" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Clan">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="Stavovi" type="sk:StavType"/>
            </xs:sequence>
            <xs:attribute name="Brojcana_oznaka" type="xs:int" use="required"/>
            <xs:attribute name="Naziv" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Stav" type="xs:string"/>
    <xs:element name="Tacka" type="xs:string"/>
    <xs:element name="Podtacka" type="xs:string"/>
    <xs:element name="Alineja" type="xs:string"/>
    <xs:complexType name="StavType">
        <xs:sequence>
            <xs:element ref="sk:Stav"/>
            <xs:sequence minOccurs="0">
                <xs:element maxOccurs="unbounded" minOccurs="2" name="Tacke" type="sk:TackaType"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TackaType">
        <xs:sequence>
            <xs:element ref="sk:Tacka"/>
            <xs:sequence minOccurs="0">
                <xs:element maxOccurs="unbounded" minOccurs="2" name="Podtacke"
                    type="sk:PodtackaType"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PodtackaType">
        <xs:sequence>
            <xs:element ref="sk:Podtacka"/>
            <xs:sequence minOccurs="0">
                <xs:element maxOccurs="unbounded" minOccurs="2" ref="sk:Alineja"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== BVezilic/XML/XML_Projekat/data/rdf/zakon_o_izvrsenju_i_obezbedjenju.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="grddl.xsl"?>
<sk:Akt xmlns:sk="http://www.ftn.uns.ac.rs/skupstina"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.w3.org/ns/rdfa#" 
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/skupstina ../xsd/akt.xsd">
    <sk:MetaPodaci vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/" 
    	about="/zakon_o_izvrsenju_i_obezbedjenju">
        <sk:DtPredlaganja property="pred:predlozen" datatype="xsi:date">1965-08-17</sk:DtPredlaganja>
        <sk:BrClanova property="pred:brakt" datatype="xsi:string">12</sk:BrClanova>
    </sk:MetaPodaci>
    <sk:Naslov>ЗАКОН О ИЗВРШЕЊУ И ОБЕЗБЕЂЕЊУ</sk:Naslov>
    <sk:Deo Redni_broj="2" Naziv="ОПШТА ПРАВИЛА ИЗВРШНОГ ПОСТУПКА">
        <sk:Glava Redni_broj="1" Naziv="ИЗВРШНА И ВЕРОДОСТОЈНА ИСПРАВА">
            <sk:Odeljak Redni_broj="1" Naziv="1. Основи за доношење решења о извршењу">
                <sk:Clan Brojcana_oznaka="40" Naziv="">
                    <sk:Stav> ĐĆ </sk:Stav>
                </sk:Clan>
            </sk:Odeljak>
            <sk:Odeljak Redni_broj="2" Naziv="2. Извршна исправа">
                <sk:Clan Brojcana_oznaka="41" Naziv="Врсте извршних исправа">
                    <sk:Stav> Извршне исправе јесу: <sk:Tacka Redni_broj="1">1) извршна судска
                            одлука и судско поравнање који гласе на давање, чињење, нечињење или
                            трпљење;</sk:Tacka>
                        <sk:Tacka Redni_broj="2">2) извршна одлука донета у прекршајном или управном
                            поступку и управно поравнање који гласе на новчану обавезу ако посебним
                            законом није друкчије одређено;</sk:Tacka>
                    </sk:Stav>
                </sk:Clan>
            </sk:Odeljak>
        </sk:Glava>
        <sk:Glava Redni_broj="2" Naziv="СРЕДСТВА И ПРЕДМЕТ ИЗВРШЕЊА">
            <sk:Clan Brojcana_oznaka="54" Naziv="Средства извршења">
                <sk:Stav>Средства извршења су радње којима се намирује потраживање извршног
                    повериоца.</sk:Stav>
                <sk:Stav>Средства извршења ради намирења новчаног потраживања јесу: продаја
                    непокретности извршног дужника, продаја покретних ствари извршног дужника,
                    пренос новчаног потраживања извршног дужника, пренос зараде извршног дужника,
                    пренос новчаних средстава с рачуна извршног дужника код банке, пренос средстава
                    са штедног улога или текућег рачуна извршног дужника, продаја финансијских
                    инструмената извршног дужника, продаја удела извршног дужника у привредним
                    субјектима и пренос потраживања извршног дужника да му се предају или испоруче
                    покретне ствари или преда непокретност.</sk:Stav>
                <sk:Stav>Средства извршења ради остваривања неновчаног потраживања јесу: предаја
                    покретних ствари извршног дужника, испражњење и предаја непокретности извршног
                    дужника, чињење, нечињење или трпљење извршног дужника, предаја детета и
                    извршење других одлука у вези с породичним односима, враћање запосленог на рад,
                    деоба сувласничке ствари и издејствовање изјаве воље.</sk:Stav>
            </sk:Clan>
            <sk:Clan Brojcana_oznaka="55" Naziv="Предмети извршења">
                <sk:Stav>Предмети извршења су ствари и права извршног дужника на којима се спроводи
                    извршење.</sk:Stav>
                <sk:Stav>Предмет извршења не могу бити ствари изван промета, објекти, оружје и
                    опрема који су намењени одбрани и безбедности Републике Србије, нити ствари које
                    су овим или другим законом изузете од извршења.</sk:Stav>
            </sk:Clan>
        </sk:Glava>
    </sk:Deo>
    <sk:Deo Redni_broj="2">
        <sk:Glava Redni_broj="1" Naziv="">
            <sk:Clan Brojcana_oznaka="1" Naziv="Предмет закона">
                <sk:Stav> Овим законом уређује се поступак у коме судови и јавни извршитељи принудно
                    намирују потраживања извршних поверилаца заснoвана на извршним и веродостојним
                    исправама (извршни поступак), поступак обезбеђења потраживања и положај јавних
                    извршитеља. </sk:Stav>
            </sk:Clan>
            <sk:Clan Brojcana_oznaka="2" Naziv="Значење појединих израза">
                <sk:Stav> Поједини изрази који се користе у овом закону имају следеће значење:
                        <sk:Tacka Redni_broj="1">1) „потраживање” означава право извршног повериоца
                        да захтева од извршног дужника одређено давање, чињење, нечињење или
                        трпљење;</sk:Tacka>
                    <sk:Tacka Redni_broj="2">2) „извршни поверилац” означава лице чије се
                        потраживање намирује у извршном поступку или обезбеђује у поступку
                        обезбеђења;</sk:Tacka>
                </sk:Stav>
            </sk:Clan>
        </sk:Glava>
        <sk:Glava Redni_broj="2" Naziv="">
            <sk:Clan Brojcana_oznaka="3"
                Naziv="Покретање и вођење извршног поступка и поступка обезбеђења">
                <sk:Stav> Извршни поступак и поступак обезбеђења покрећу се тако што извршни
                    поверилац подноси предлог за извршење на основу извршне или веродостојне исправе
                    или предлог за обезбеђење, а по службеној дужности покрећу се само ако је
                    законом одређено. </sk:Stav>
            </sk:Clan>
            <sk:Clan Brojcana_oznaka="4" Naziv="Надлежност за спровођење извршења">
                <sk:Stav> Суд је искључиво надлежан за извршење заједничке продаје непокретности и
                    покретних ствари, чињења, нечињења или трпљења (чл. 359–367) и извршење извршних
                    исправа у вези с породичним односима и враћањем запосленог на рад. </sk:Stav>
            </sk:Clan>
        </sk:Glava>
    </sk:Deo>
</sk:Akt>

=== BVezilic/XML/XML_Projekat/data/xml/zakon_o_policiji.xml
<?xml version="1.0" encoding="UTF-8"?>
<sk:Akt xmlns:sk="http://www.ftn.uns.ac.rs/skupstina"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/skupstina ../xsd/akt.xsd"
    xmlns="http://www.w3.org/ns/rdfa#" 
    xmlns:pred="http://www.ftn.uns.ac.rs/skupstina/predikat">
    <sk:MetaPodaci
        about="http://www.ftn.uns.ac.rs/skupstina/zakon_o_policiji">
        <sk:DatumPredlaganja property="pred:predlozen" datatype="xsi:date">1995-01-12</sk:DatumPredlaganja>
    </sk:MetaPodaci>
    <sk:Naslov>ZAKON O POLICIJI</sk:Naslov>
    <sk:Glava Redni_broj="1" Naziv="OSNOVNE ODREDBE" Redna_oznaka="I.">
        <sk:Clan Redni_broj="1" Redna_oznaka="1." Naziv="Predmet zakona">
            <sk:Stav Redni_broj="1">Ovim zakonom uređuju se unutrašnji poslovi, organizacija i
                nadležnost Ministarstva unutrašnjih poslova (u daljem tekstu: Ministarstvo),
                policijski poslovi, organizacija i nadležnost Policije, kao i druga pitanja od
                značaja za rad Policije i Ministarstva.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="2" Redna_oznaka="2." Naziv="Pojam unutrašnjih poslova">
            <sk:Stav Redni_broj="1">Unutrašnji poslovi su zakonom utvrđeni poslovi državne uprave,
                koje obavlja Ministarstvo, a čijim obavljanjem se ostvaruje i unapređuje bezbednost
                građana i imovine, pruža podrška vladavini prava i obezbeđuje ostvarivanje Ustavom i
                zakonom utvrđenih ljudskih i manjinskih prava i sloboda, kao i drugi, sa njima
                povezani poslovi iz utvrđenog delokruga i nadležnosti Ministarstva.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="3" Redna_oznaka="3." Naziv="Policija">
            <sk:Stav Redni_broj="1">Policija je centralna organizaciona jedinica Ministarstva koja u
                obavljanju unutrašnjih odnosno policijskih poslova, štiti i unapređuje bezbednost
                građana i imovine, poštujući Ustavom zajemčena ljudska i manjinska prava i slobode i
                druge zaštićene vrednosti u demokratskom društvu, uz mogućnost na Ustavu i zakonu
                zasnovane upotrebe sredstava prinude.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="6" Redna_oznaka="6." Naziv="Informisanje o radu Ministarstva">
            <sk:Stav Redni_broj="1">Rad Ministarstva je javan.</sk:Stav>
            <sk:Stav Redni_broj="2">Ministarstvo redovno blagovremeno i potpuno obaveštava javnost o
                svom radu, osim u slučajevima preduzimanja mera i radnji u skladu sa zakonom kojim
                se uređuje krivični postupak i kada bi to onemogućilo neometan operativni rad
                Policije, ili ako bi se time: <sk:Tacka Redni_broj="1" Redna_oznaka="1)">povredio
                    propis o tajnosti podataka;</sk:Tacka>
                <sk:Tacka Redni_broj="2" Redna_oznaka="2)">povredilo dostojanstvo
                    građana;</sk:Tacka>
                <sk:Tacka Redni_broj="3" Redna_oznaka="3)">ugrozilo pravo na ličnu slobodu i
                    bezbednost.</sk:Tacka></sk:Stav>
            <sk:Stav Redni_broj="3">Ministarstvo jednom godišnje, a najkasnije u roku od tri meseca
                od završetka kalendarske godine, objavljuje: <sk:Tacka Redni_broj="1"
                    Redna_oznaka="1)">izveštaj o stanju bezbednosti u Republici Srbiji koji na
                    transparentan i javan način obaveštava javnost o proceni bezbednosti, trendovima
                    kretanja kriminala i drugih bezbednosnih pojava od značaja za bezbednost i prava
                    građana;</sk:Tacka>
                <sk:Tacka Redni_broj="2" Redna_oznaka="2)">izveštaj o radu Ministarstva, koji na
                    transparentan i javan način obaveštava javnost o razvoju policije, statističkim
                    podacima o sprovedenim aktivnostima i postignutim
                rezultatima.</sk:Tacka></sk:Stav>
            <sk:Stav Redni_broj="4">Pored izveštaja iz stava 3. ovog člana, Ministarstvo je u
                obavezi da objavi na svojoj internet prezentaciji i tromesečne informacije o radu,
                koje usvaja nadležni odbor Narodne skupštine Republike Srbije za unutrašnje
                poslove.</sk:Stav>
        </sk:Clan>
    </sk:Glava>
    <sk:Glava Redni_broj="2" Naziv="ORGANIZACIJA I NADLEŽNOST MINISTARSTVA" Redna_oznaka="II.">
        <sk:Clan Redni_broj="8" Redna_oznaka="8." Naziv="Organizacija Ministarstva">
            <sk:Stav Redni_broj="1">Za obavljanje poslova iz nadležnosti Ministarstva, obrazuju se
                unutrašnje organizacione jedinice.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="9" Redna_oznaka="9.">
            <sk:Stav Redni_broj="1">Vlada propisuje načela za unutrašnje uređenje Ministarstva, kao
                i vrste organizacionih jedinica, sedišta i područja za koja se obrazuju te
                jedinice.</sk:Stav>
            <sk:Stav Redni_broj="2">Pravilnikom o unutrašnjem uređenju i sistematizaciji radnih
                mesta, ministar - po prethodno pribavljenoj saglasnosti Vlade, utvrđuje delokrug i
                kategorizaciju organizacionih jedinica Ministarstva, broj, sistematizaciju, vrstu,
                odnosno status i opis radnih mesta, radna mesta za koja se predviđaju posebni uslovi
                za njihovo popunjavanje, način rukovođenja, planiranja i izvršavanja
                poslova.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="10" Redna_oznaka="10." Naziv="Zaposleni u Ministarstvu">
            <sk:Stav Redni_broj="1">Zaposleni u Ministarstvu jesu policijski službenici, državni
                službenici i nameštenici.</sk:Stav>
            <sk:Stav Redni_broj="2">Policijski službenici jesu: <sk:Tacka Redni_broj="1"
                    Redna_oznaka="1)">lica koja obavljaju policijske poslove u statusu ovlašćenih
                    službenih lica i primenjuju policijska ovlašćenja (ovlašćena službena lica -
                    OSL);</sk:Tacka>
                <sk:Tacka Redni_broj="2" Redna_oznaka="2)">lica na posebnim dužnostima koja
                    obavljaju druge unutrašnje poslove u neposrednoj vezi sa policijskim poslovima
                    (lica na posebnim dužnostima - PD).</sk:Tacka></sk:Stav>
            <sk:Stav Redni_broj="3">Policijski službenici u statusu ovlašćenih službenih lica,
                moraju imati najmanje završenu policijsku obuku osnovnog nivoa.</sk:Stav>
            <sk:Stav Redni_broj="4">Državni službenici jesu lica, koja u tom statusu, obavljaju
                ostale poslove iz delokruga Ministarstva i sa njima povezane opšte, pravne,
                informatičke, materijalno – finansijske, računovodstvene i administrativne
                poslove.</sk:Stav>
            <sk:Stav Redni_broj="5">Nameštenici jesu lica, koja, u tom statusu, obavljaju prateće
                pomoćno - tehničke poslove.</sk:Stav>
        </sk:Clan>
    </sk:Glava>
</sk:Akt>

=== BVezilic/XML/XML_Projekat/data/xml/zakon_o_zastiti_zemljista.xml
<?xml version="1.0" encoding="UTF-8"?>
<sk:Akt xmlns:sk="http://www.ftn.uns.ac.rs/skupstina"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/skupstina ../xsd/akt.xsd">
    <sk:Naslov>ZAKON O ZAŠTITI ZEMLjIŠTA</sk:Naslov>
    <sk:Glava Redni_broj="1" Redna_oznaka="I." Naziv="OSNOVNE ODREDBE">
        <sk:Clan Redni_broj="1" Redna_oznaka="1." Naziv="Predmet zakona">
            <sk:Stav Redni_broj="1">Ovim zakonom uređuje se zaštita zemljišta, sistematsko praćenje stanja i kvaliteta
                zemljišta, mere sanacije, remedijacije, rekultivacije, inspekcijski nadzor i druga
                pitanja od značaja za zaštitu i očuvanje zemljišta kao prirodnog resursa od nacionalnog
                interesa.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="2" Redna_oznaka="2." Naziv="Primena zakona">
            <sk:Stav Redni_broj="1">Odredbe ovog zakona primenjuju se na sve tipove zemljišta Republike Srbije kao
                prirodni resurs, bez obzira na oblik svojine, njegovu namenu i korišćenje.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="3" Redna_oznaka="3." Naziv="Cilj zakona">
            <sk:Stav Redni_broj="1"> Cilj ovog zakona je da se očuvaju površine i funkcije zemljišta kao prirodnog
                resursa i da se spreče ili otklone štetne promene u zemljištu koje mogu da nastanu
                kao posledica: <sk:Tacka Redni_broj="1" Redna_oznaka="1)">erozionih procesa;</sk:Tacka>
                <sk:Tacka Redni_broj="2" Redna_oznaka="2)">smanjenja sadržaja organske materije u
                    zemljištu;</sk:Tacka>
                <sk:Tacka Redni_broj="3" Redna_oznaka="3)">neprimerene poljoprivredne i šumske proizvodnje
                    (neadekvatne i nekontrolisane agrotehničke i meliorativne mere, krčenje šuma i
                    dr);</sk:Tacka>
                <sk:Tacka Redni_broj="4" Redna_oznaka="4)">nekontrolisane promene namene, upravljanja i korišćenja
                    zemljišta;</sk:Tacka>
                <sk:Tacka Redni_broj="5" Redna_oznaka="5)">neplanske urbanizacije, odnosno izgradnje i razvoja
                    infrastrukture;</sk:Tacka>
                <sk:Tacka Redni_broj="6" Redna_oznaka="6)">zakiseljavanja (acidifikacija), zaslanjivanja (salinizacija)
                    i alkalizacije zemljišta;</sk:Tacka>
                <sk:Tacka Redni_broj="7" Redna_oznaka="7)">sabijanja zemljišta, klizišta i odrona;</sk:Tacka>
                <sk:Tacka Redni_broj="8" Redna_oznaka="8)">požara i hemijskih udesa;</sk:Tacka>
                <sk:Tacka Redni_broj="9" Redna_oznaka="9)">zagađenja (nastalog upravljanjem otpadom, ispuštanjem
                    otpadnih voda, emisijama iz tačkastih i difuznih izvora, hemijskog zagađenja i
                    dr);</sk:Tacka>
                <sk:Tacka Redni_broj="10" Redna_oznaka="10)">eksploatacije mineralnih i organskih
                    sirovina;</sk:Tacka>
                <sk:Tacka Redni_broj="11" Redna_oznaka="11)">eksploatacije šljunka, kamena i peska;</sk:Tacka>
                <sk:Tacka Redni_broj="12" Redna_oznaka="12)">nedozvoljenih arheoloških iskopavanja i istraživanja i
                    dr.</sk:Tacka>
            </sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="4" Redna_oznaka="4." Naziv="Značenje izraza">
            <sk:Stav Redni_broj="1">Izrazi upotrebljeni u ovom zakonu imaju sledeće značenje:
                <sk:Tacka Redni_broj="1" Redna_oznaka="1)">aktivnost koja utiče na zemljište jeste svaki privremeni,
                    povremeni ili stalni zahvat kojim se menja ili se može promeniti stanje i
                    uslovi na nekoj lokaciji;</sk:Tacka>
                <sk:Tacka Redni_broj="2" Redna_oznaka="2)">granične vrednosti jesu vrednosti zagađujućih, štetnih i opasnih
                    materija u zemljištu koje mogu biti:
                    <sk:Podtacka Redni_broj="1" Redna_oznaka="(1)">granična minimalna vrednost jeste vrednost zagađujućih,
                        štetnih i opasnih materija u zemljištu koja se bazira na njihovom prirodnom
                        sadržaju i predstavlja vrednost za nezagađeno zemljište, pri čemu nije ili je
                        minimalno narušena ekološka ravnoteža;</sk:Podtacka>
                    <sk:Podtacka Redni_broj="2" Redna_oznaka="(2)">granična maksimalna vrednost jeste vrednost zagađujućih,
                        štetnih i opasnih materija u zemljištu čije prekoračenje ukazuje na nivo
                        kontaminacije koji narušava ekološku ravnotežu, nameće dodatna ispitivanja
                        tog zemljišta kao i ograničenja u načinu upravljanja;</sk:Podtacka></sk:Tacka>
                <sk:Tacka Redni_broj="3" Redna_oznaka="3)">degradacija zemljišta jeste proces narušavanja kvaliteta i
                    funkcija zemljišta koji nastaje prirodnim putem ili ljudskom aktivnošću
                    ili je posledica nepreduzimanja mera za sprečavanje štetnih posledica;</sk:Tacka>
                <sk:Tacka Redni_broj="4" Redna_oznaka="4)">dobra stručna praksa predstavlja primenu naučnih, tehničkih i
                    biotehničkih mera i/ili mera upravljanja i korišćenja zemljišta u cilju
                    očuvanja i unapređivanja kvaliteta zemljišta;</sk:Tacka>
            </sk:Stav>
        </sk:Clan>
    </sk:Glava>
    <sk:Glava Redni_broj="2" Redna_oznaka="II." Naziv="PREVENTIVNE MERE ZAŠTITE ZEMLjIŠTA">
        <sk:Clan Redni_broj="8" Redna_oznaka="8.">
            <sk:Stav Redni_broj="1">Preventivne mere zaštite zemljišta obuhvataju planiranje i integrisanje zaštite
                zemljišta u sektorske politike i planove, utvrđivanje ispunjenosti uslova zaštite
                zemljišta, donošenje planskih i programskih dokumenata za zaštitu zemljišta.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="9" Redna_oznaka="9." Naziv="Uređenje prostora i korišćenje zemljišta">
            <sk:Stav Redni_broj="1">Sprečavanje degradacije zemljišta postiže se planiranjem, uređenjem prostora,
                korišćenjem prirodnih resursa i dobara u skladu sa prostornim, urbanističkim i drugim
                planskim dokumentima (u daljem tekstu: planska dokumenta), koji se donose u skladu sa
                posebnim zakonima.</sk:Stav>
            <sk:Stav Redni_broj="2">Mere i uslovi zaštite zemljišta, radi održivog korišćenja zemljišta su sastavni
                deo planskih dokumenata.</sk:Stav>
            <sk:Stav Redni_broj="3">Ministarstvo nadležno za poslove zaštite životne sredine (u daljem tekstu:
                Ministarstvo), nadležni organ autonomne pokrajine, odnosno jedinice lokalne
                samouprave učestvuju u postupku pripreme i donošenja planskih dokumenata, na način
                određen zakonom.</sk:Stav>
        </sk:Clan>
        <sk:Clan Redni_broj="10" Redna_oznaka="10." Naziv="Promena namene zemljišta">
            <sk:Stav Redni_broj="1">Zemljište se koristi prema nameni određenoj u planskim dokumentima.</sk:Stav>
            <sk:Stav Redni_broj="2">Kada se planskim dokumentom menja namena zemljišta, organ nadležan za donošenje
                planskog dokumenta, dužan je da u postupku odlučivanja poseduje saglasnost
                Ministarstva.</sk:Stav>
            <sk:Stav Redni_broj="3">Saglasnost iz stava 2. ovog člana, Ministarstvo daje na zahtev nadležnog
                organa, po pribavljenom mišljenju od stručnih i naučnih organizacija o postojećem
                faktičkom stanju zemljišta i proceni mogućnosti promene namene zemljišta, a na osnovu
                podataka iz informacionog sistema za zemljište.</sk:Stav>
        </sk:Clan>
    </sk:Glava>
</sk:Akt>
